name: buildandDeploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ build ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Artifactory
        uses: docker/login-action@v1 
        with:
          registry: artifactory.internal.sysdig.com
          username: david.lorite@sysdig.com
          password: ${{ secrets.ARTI_TOKEN }}
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: ./build
          file: ./build/Dockerfile
          push: false
          tags: artifactory.internal.sysdig.com/jmx-exporter:latest
      - name: Push the image
        run: |
          docker push artifactory.internal.sysdig.com/jmx-exporter:latest